[package]
name = "browser-proto"
version = "0.0.0"
publish = false
edition = "2024"

[dependencies]
roam = { git = "https://github.com/bearcove/roam", branch = "main" }
facet = { git = "https://github.com/facet-rs/facet", branch = "main" }
hotmeal = { path = "../.." }
